# Default values for tnlab.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

grafana:
  rbac:
    pspEnabled: false
  adminUser: tnlab
  admin:
    existingSecret: grafana-creds
    userKey: username
    passwordKey: password
  ingress:
    enabled: true
    ingressClassName: nginx
    labels: {}
    path: /
    pathType: Prefix
    hosts:
      - grafana.local
    extraPaths: []
    tls: []

dssSecret:
  name: dss-creds
  username: tnlab

dss:
  env:
    DSS_SERVER_URL: https://localhost:9443
    DSS_REVERSEPROXY: localhost
  ingress:
    enabled: true
    host: dss.local
    tls: []
    ingressClassName: nginx

nifi:
  postStart: /opt/nifi/; wget -P /opt/nifi/ https://jdbc.postgresql.org/download/postgresql-42.2.5.jar
  persistence:
    enabled: true
    subPath:
      enabled: true
      size: 128Gi
  zookeeper:
    enabled: false
  auth:
    singleUser:
      username: tnlab
      password: tnlabpassword # Must have at least 12 characters
  ingress:
    enabled: true
    tls: []
    hosts:
      - nifi.local
    path: /
    className: nginx

nuclio:
  dashboard:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      path: /
      hosts:
        - nuclio.local
      tls: []
  basicAuth:
    username: ""
    password: ""

minio:
  enabled: true
  rootUser: tnlab
  existingSecret: minio-creds-secret
  mode: standalone
  replicas: 1
  ingress:
    enabled: true
    hosts:
      - minio-api.local
    tls: []
    ingressClassName: nginx
  consoleIngress:
    enabled: true
    hosts:
      - minio.local
    tls: []
    ingressClassName: nginx
  persistence:
    enabled: true
    size: 128Gi
  resources:
    requests:
      memory: 0.5Gi
    limits:
      memory: 4Gi
  service:
    type: ClusterIP
    port: 9000
  consoleService:
    type: ClusterIP
    port: 9001

dremio:
  ingress:
    enabled: true
    hosts:
      - host: dremio.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    className: nginx

mysqlchart:
  dssCreds:
    dssDbUsername: tnlab
    dssDbPassword: tnlabpassword

# Postgres automatically generates a secret with the password for the user tnlab (database: tnlab)
