# MySqlDeployment
deploy:
  type: Recreate
  image: mysql:5.7
  mountPath: /var/lib/mysql
  claimName: mysql-pv-claim
mysqlCreds:
  existingSecret: ""
  passwordKey: ""

# Storage
persistentVolume:
  name: mysql-pv-volume
  type: local
  storageClassName: default
  storage: 8Gi
  accessModes: ReadWriteOnce
  path: "/mnt/data"
  reclaimPolicy: Delete
persistentVolumeClaim:
  name: mysql-pv-claim
  storageClassName: default
  accessModes: ReadWriteOnce
  storage: 8Gi

# Credentials
mysqlcreds:
  username: root
  password: pwd
dssCreds:
  dssDbUsername: ""
  dssDbPassword: ""

# Global
global:
  imagePullSecret: ""
  mySql:
    service: mysql
    port: 3306
    app: mysql




