{{- if not .Values.mysqlCreds.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  username: {{ .Values.mysqlcreds.username | b64enc }}
  password: {{ .Values.mysqlcreds.password | b64enc }}
{{- end }}