apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: dhmigration-postgres-cluster
spec:
  teamId: "dhmigration"
  volume:
    size: 8Gi
  numberOfInstances: 1
  users:
    dhmigration:
    - superuser
    - createdb
  databases:
    dhmigration: dhmigration
  preparedDatabases:
    dhmigration:
      schemas:
        public:
          defaultRoles: false
      extensions:
        timescaledb: public
        postgis: public
  postgresql:
    version: "14"