apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: tnlab-postgres-cluster
spec:
  resources:
    limits:
      cpu: "2"
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 100Mi
  teamId: "tnlab"
  volume:
    size: 512Gi
  numberOfInstances: 3
  users:
    tnlab:
    - superuser
    - createdb
  databases:
    tnlab: tnlab
  preparedDatabases:
    tnlab:
      schemas:
        public:
          defaultRoles: false
      extensions:
        timescaledb: public
        postgis: public
  postgresql:
    version: "14"
