apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dssSecret.name }}
type: Opaque
data:
  username: {{ .Values.dssSecret.username | b64enc }}
  password: {{ .Values.dssSecret.password | b64enc }}