apiVersion: v1
kind: Secret
metadata:
  name: grafana-creds
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
type: Opaque
data:
  username: {{ .Values.grafana.adminUser | b64enc }}
  password: {{ randAlphaNum 12 | nospace | b64enc }}
