apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.minio.secrets.name }}
type: Opaque
data:
  ## Access Key for MinIO Tenant
  accesskey: {{ .Values.minio.secrets.accessKey | b64enc }}
  ## Secret Key for MinIO Tenant
  secretkey: {{ .Values.minio.secrets.secretKey | b64enc }}