apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/upstream-vhost: "localhost:9443"
    nginx.ingress.kubernetes.io/proxy-redirect-from: "https://localhost:9443"
    nginx.ingress.kubernetes.io/proxy-redirect-to: "https://{{ .Values.minio.ingress.host }}"
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: {{ .Release.Name}}-minio
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.minio.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: myminio-console
            port:
              name: https-console
        path: /
        pathType: ImplementationSpecific