apiVersion: v1
kind: Secret
metadata:
  name: minio-creds-secret
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
type: Opaque
data:
  rootUser: {{ .Values.minio.rootUser | b64enc }}
  rootPassword: {{ randAlphaNum 12 | nospace | b64enc }}
