{{- if and .Values.nuclio.basicAuth.username .Values.nuclio.basicAuth.password }}
apiVersion: v1
data:
  auth: {{ htpasswd .Values.nuclio.basicAuth.username .Values.nuclio.basicAuth.password | b64enc }}
kind: Secret
metadata:
  name: nuclio-auth-secret
{{- end }}
