{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/upstream-vhost: "localhost:9443"
    nginx.ingress.kubernetes.io/proxy-redirect-from: "https://localhost:9443"
    nginx.ingress.kubernetes.io/proxy-redirect-to: "https://dss.local"
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: {{ .Release.Name}}-dss
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ template "dss.fullname" . }}
            port:
              name: https-servlet
        path: /
        pathType: ImplementationSpecific
{{- end }}